### ISSUE TITLE
`:BuffergatorTabsToggle` doesn't seem to work

### ISSUE THREAD

**Issue by joech4n** [jeetsukumaran/vim-buffergator#32]
`:BuffergatorTabsToggle` doesn't seem to work in the latest version... any ideas why?

# Workaround

I've made a toggle in the meantime in my `.vimrc`:

    nnoremap <leader>tl :call BgTabCabinetToggle()<cr>
    let g:bgTabCabinet_is_open = 1
    function! BgTabCabinetToggle()
        if g:bgTabCabinet_is_open
            BuffergatorTabsOpen
            let g:bgTabCabinet_is_open = 0
        else
            BuffergatorTabsClose
            let g:bgTabCabinet_is_open = 1
        endif
    endfunction

# Diagnostic info

    ~  vim --version
    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 22 2015 15:43:47)
    MacOS X (unix) version
    Included patches: 1-488
    Compiled by Homebrew
    Huge version without GUI.  Features included (+) or not (-):
    +acl             +farsi           +mouse_netterm   +syntax
    +arabic          +file_in_path    +mouse_sgr       +tag_binary
    +autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
    -balloon_eval    +float           +mouse_urxvt     -tag_any_white
    -browse          +folding         +mouse_xterm     -tcl
    ++builtin_terms  -footer          +multi_byte      +terminfo
    +byte_offset     +fork()          +multi_lang      +termresponse
    +cindent         -gettext         -mzscheme        +textobjects
    -clientserver    -hangul_input    +netbeans_intg   +title
    +clipboard       +iconv           +path_extra      -toolbar
    +cmdline_compl   +insert_expand   +perl            +user_commands
    +cmdline_hist    +jumplist        +persistent_undo +vertsplit
    +cmdline_info    +keymap          +postscript      +virtualedit
    +comments        +langmap         +printer         +visual
    +conceal         +libcall         +profile         +visualextra
    +cryptv          +linebreak       +python          +viminfo
    +cscope          +lispindent      -python3         +vreplace
    +cursorbind      +listcmds        +quickfix        +wildignore
    +cursorshape     +localmap        +reltime         +wildmenu
    +dialog_con      -lua             +rightleft       +windows
    +diff            +menu            +ruby            +writebackup
    +digraphs        +mksession       +scrollbind      -X11
    -dnd             +modify_fname    +signs           -xfontset
    -ebcdic          +mouse           +smartindent     -xim
    +emacs_tags      -mouseshape      -sniff           -xsmp
    +eval            +mouse_dec       +startuptime     -xterm_clipboard
    +ex_extra        -mouse_gpm       +statusline      -xterm_save
    +extra_search    -mouse_jsbterm   -sun_workshop    -xpm
       system vimrc file: "$VIM/vimrc"
         user vimrc file: "$HOME/.vimrc"
     2nd user vimrc file: "~/.vim/vimrc"
          user exrc file: "$HOME/.exrc"
      fall-back for $VIM: "/usr/local/share/vim"
    Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.9 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
    Linking: /usr/bin/clang   -L. -L/usr/local/lib -L/usr/local/lib -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector -L/usr/local/lib  -L/System/Library/Perl/5.16/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby.2.0.0 -lobjc

    ~  git -C ~/.vim/bundle/vim-buffergator log -1 |cat
    commit 5db257e14beb881a85ea8948af38ea8e1aec0b62
    Merge: f883e59 2cb134a
    Author: Jeet Sukumaran <jeetsukumaran@gmail.com>
    Date:   Mon Jan 19 22:07:56 2015 -0500
    
        Merge branch 'master' of https://github.com/jeetsukumaran/vim-buffergator

**Edit**: Initial `let g:bgTabCabinet_is_open = 0` should be `let g:bgTabCabinet_is_open = 1`

**Comment by jeetsukumaran** [comment]
When you say it doesn't work, what exactly do you mean? Does not open? Or throws an exception?

**Comment by joech4n** [comment]
Sorry for not clarifying! Yes, it doesn't open. No action or output.

**Comment by jeetsukumaran** [comment]
Ok, this should be fixed in the latest revision. Lots of little glitches between toggling, opening, closing, and generally cycling between the tab and buffer listings should be addressed now. Let me know if it works.

**Comment by joech4n** [comment]
Works for me now! Thank you! :+1:
