### ISSUE TITLE
Panel showing the buffers wrong hsplit_size, correct after :source

### ISSUE THREAD

**Issue by dewey** [jeetsukumaran/vim-buffergator#33]
Hello,

I just setup vim-buffergator and it's mostly working great but I'm running into one problem where buffergator is ignoring my settings. My configuration looks like this: https://github.com/dewey/dotfiles/blob/master/vim/.vimrc#L130

Steps to reproduce:
- I start vim, hit `<Leader> + b` to show the buffer panel, which shows up at the top like defined in the configuration file. But it's the default size and not `7` like the config says. If I close it with `<Leader> + B` and then run `:source ~/.vimrc` and open it again with `<Leader> + b` it'll have the correct size.
If I start vim and `:echo g:buffergator_hsplit_size` it'll reply with the correct value, 7.

Another thing I noticed is that `g:buffergator_autodismiss_on_select` is also getting ignored, it's not hidden once I select a buffer. It's obviously not ignoring `let g:buffergator_viewport_split_policy = "T"` because that seems to work.

Any idea what's wrong there? Thanks!

**Comment by jeetsukumaran** [comment]
I have fixed the first issue.

With the second, your configuration has [`let g:buffergator_autodismiss_on_select = 0`](https://github.com/dewey/dotfiles/blob/master/vim/.vimrc#L124), so you are explicitly instructing the Buffergator window *NOT* be hidden on selection of file, which is, indeed, the behavior you describe.

Did you mean to have `let g:buffergator_autodismiss_on_select = 1` instead?

**Comment by dewey** [comment]
Just updated to the latest version and it's working now, thanks for the very quick fix! And about that second part...you are right, I guess I was a bit too sleepy when I changed that setting.

Issue closed by commit f7b47666e62b36e6b825a7803a4f82f83ca448aa

Thanks again!
