### ISSUE TITLE
buffergator_mru_cycle_loop doesn't seem to work is 2.4.1

### ISSUE THREAD

**Issue by npearson72** [jeetsukumaran/vim-buffergator#34]
The `]b` and `[b` commands don't seem to work for me. Can anyone else confirm?

**Comment by jeetsukumaran** [comment]
I have to say that this is one of the most non-informative issues that I have ever received on GitHub. You really need to provide more context and details if you expect this to be addressed.

**Comment by npearson72** [comment]
Wow, never mind. This plugin isn't so good that it's worth putting up with smug arrogant pricks like you.

**Comment by jeetsukumaran** [comment]
Sorry to hear that. Hopefully someday you find a plugin good enough to be worth putting up with smug arrogant pricks like me. In the mean time, if you care to take the time and trouble to write a decent issue request, I will be happy to look into the problem.

**Comment by npearson72** [comment]
That would be big "no thanks". Already deleted your plugin.

**Comment by jeetsukumaran** [comment]
Ok. Again, sorry. I will consider devoting the next several decades of my life, forgoing sleep, food, and even my day job, trying to write a free, open-source plugin worthy of you putting up with smug arrogant pricks like.

**Comment by npearson72** [comment]
Apology accepted. I'm still moving on. Good luck with your plan there.
